// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NewAppleSupportTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void newAppleSupport() {
    driver.get("https://www.apple.com/br/");
    driver.manage().window().setSize(new Dimension(1294, 741));
    driver.findElement(By.linkText("Suporte")).click();
    driver.findElement(By.cssSelector(".as-imagegrid-item:nth-child(2) .as-imagegrid-img")).click();
    driver.findElement(By.cssSelector(".as-content-block:nth-child(4) .icon-copy")).click();
    driver.findElement(By.cssSelector(".as-content-block:nth-child(3) .column:nth-child(1) .icon-copy")).click();
    driver.findElement(By.cssSelector("#sections > div:nth-child(2) > h2")).click();
    driver.findElement(By.cssSelector("#sections > div:nth-child(2) > h2")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > h2")).click();
    driver.findElement(By.id("questionInputField")).click();
    driver.findElement(By.id("questionInputField")).sendKeys("test");
    driver.findElement(By.cssSelector(".questionSubmitFormButton")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.id("account_name_text_field")).sendKeys("tomasandrade@gmail.com");
    driver.findElement(By.id("account_name_text_field")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("password_text_field")).sendKeys("gwaqgWQAGQ");
    driver.findElement(By.id("password_text_field")).sendKeys(Keys.ENTER);
  }
}
